set -g status-style "bg=#1F2430,fg=#CCCAC2"
set -g status-left-style NONE
set -g status-right-style NONE
set -g message-style "bg=#5CCFE6,fg=#CCCAC2"
set -g message-command-style "bg=#1F2430,fg=#CCCAC2"
set -g pane-border-style "fg=#CCCAC2"
set -g pane-active-border-style "fg=#5CCFE6"
set -g window-status-activity-style "fg=#CCCAC2,bg=#1F2430"
set -g window-status-style "fg=#CCCAC2,bg=#1F2430"
set -g window-status-current-format "#[fg=#1F2430,bg=#5CCFE6,bold] #I #[fg=#CCCAC2,bg=#1F2430] #W #F "
set -g window-status-format "#[fg=#CCCAC2,bg=#1F2430] #I #[fg=#CCCAC2,bg=#1F2430] #W #F "
set -g status-left "#[fg=#1F2430,bg=#5CCFE6,bold] #S #[fg=#5CCFE6,bg=#1F2430]"
set -g status-right "#[fg=#D5FF80,bg=#1F2430] %Y-%m-%d #[fg=#5CCFE6,bg=#1F2430]  #[fg=#1F2430,bg=#5CCFE6,bold] %H:%M "
set -g mode-style "fg=#D5FF80,bg=#1F2430"
set -g window-status-bell-style "fg=#F28779,bg=#1F2430,bold"
