set -g status-style "bg=#0B0E14,fg=#BFBDB6"
set -g status-left-style NONE
set -g status-right-style NONE
set -g message-style "bg=#39BAE6,fg=#BFBDB6"
set -g message-command-style "bg=#0B0E14,fg=#BFBDB6"
set -g pane-border-style "fg=#BFBDB6"
set -g pane-active-border-style "fg=#39BAE6"
set -g window-status-activity-style "fg=#BFBDB6,bg=#0B0E14"
set -g window-status-style "fg=#BFBDB6,bg=#0B0E14"
set -g window-status-current-format "#[fg=#0B0E14,bg=#39BAE6,bold] #I #[fg=#BFBDB6,bg=#0B0E14] #W #F "
set -g window-status-format "#[fg=#BFBDB6,bg=#0B0E14] #I #[fg=#BFBDB6,bg=#0B0E14] #W #F "
set -g status-left "#[fg=#0B0E14,bg=#39BAE6,bold] #S #[fg=#39BAE6,bg=#0B0E14]"
set -g status-right "#[fg=#AAD94C,bg=#0B0E14] %Y-%m-%d #[fg=#39BAE6,bg=#0B0E14]  #[fg=#0B0E14,bg=#39BAE6,bold] %H:%M "
set -g mode-style "fg=#AAD94C,bg=#0B0E14"
set -g window-status-bell-style "fg=#F07178,bg=#0B0E14,bold"
