set -g status-style "bg=#F8F9FA,fg=#5C6166"
set -g status-left-style NONE
set -g status-right-style NONE
set -g message-style "bg=#55B4D4,fg=#5C6166"
set -g message-command-style "bg=#F8F9FA,fg=#5C6166"
set -g pane-border-style "fg=#5C6166"
set -g pane-active-border-style "fg=#55B4D4"
set -g window-status-activity-style "fg=#5C6166,bg=#F8F9FA"
set -g window-status-style "fg=#5C6166,bg=#F8F9FA"
set -g window-status-current-format "#[fg=#F8F9FA,bg=#55B4D4,bold] #I #[fg=#5C6166,bg=#F8F9FA] #W #F "
set -g window-status-format "#[fg=#5C6166,bg=#F8F9FA] #I #[fg=#5C6166,bg=#F8F9FA] #W #F "
set -g status-left "#[fg=#F8F9FA,bg=#55B4D4,bold] #S #[fg=#55B4D4,bg=#F8F9FA]"
set -g status-right "#[fg=#86B300,bg=#F8F9FA] %Y-%m-%d #[fg=#55B4D4,bg=#F8F9FA]  #[fg=#F8F9FA,bg=#55B4D4,bold] %H:%M "
set -g mode-style "fg=#86B300,bg=#F8F9FA"
set -g window-status-bell-style "fg=#F07171,bg=#F8F9FA,bold"
