set -g status-style "bg=#181825,fg=#cdd6f4"
set -g status-left-style NONE
set -g status-right-style NONE
set -g message-style "bg=#585b70,fg=#cdd6f4"
set -g message-command-style "bg=#181825,fg=#cdd6f4"
set -g pane-border-style "fg=#585b70"
set -g pane-active-border-style "fg=#89b4fa"
set -g window-status-activity-style "fg=#cdd6f4,bg=#181825"
set -g window-status-style "fg=#cdd6f4,bg=#181825"
set -g window-status-current-format "#[fg=#181825,bg=#89b4fa,bold] #I #[fg=#cdd6f4,bg=#181825] #W #F "
set -g window-status-format "#[fg=#cdd6f4,bg=#181825] #I #[fg=#cdd6f4,bg=#181825] #W #F "
set -g status-left "#[fg=#181825,bg=#89b4fa,bold] #S #[fg=#89b4fa,bg=#181825]"
set -g status-right "#[fg=#a6e3a1,bg=#181825] %Y-%m-%d #[fg=#89b4fa,bg=#181825]  #[fg=#181825,bg=#89b4fa,bold] %H:%M "
set -g mode-style "fg=#a6e3a1,bg=#181825"
set -g window-status-bell-style "fg=#f38ba8,bg=#181825,bold"
