set -g status-style "bg=#e6e9ef,fg=#4c4f69"
set -g status-left-style NONE
set -g status-right-style NONE
set -g message-style "bg=#acb0be,fg=#4c4f69"
set -g message-command-style "bg=#e6e9ef,fg=#4c4f69"
set -g pane-border-style "fg=#acb0be"
set -g pane-active-border-style "fg=#1e66f5"
set -g window-status-activity-style "fg=#4c4f69,bg=#e6e9ef"
set -g window-status-style "fg=#4c4f69,bg=#e6e9ef"
set -g window-status-current-format "#[fg=#e6e9ef,bg=#1e66f5,bold] #I #[fg=#4c4f69,bg=#e6e9ef] #W #F "
set -g window-status-format "#[fg=#4c4f69,bg=#e6e9ef] #I #[fg=#4c4f69,bg=#e6e9ef] #W #F "
set -g status-left "#[fg=#e6e9ef,bg=#1e66f5,bold] #S #[fg=#1e66f5,bg=#e6e9ef]"
set -g status-right "#[fg=#40a02b,bg=#e6e9ef] %Y-%m-%d #[fg=#1e66f5,bg=#e6e9ef]  #[fg=#e6e9ef,bg=#1e66f5,bold] %H:%M "
set -g mode-style "fg=#40a02b,bg=#e6e9ef"
set -g window-status-bell-style "fg=#d20f39,bg=#e6e9ef,bold"
