set -g status-style "bg=#1e2030,fg=#cad3f5"
set -g status-left-style NONE
set -g status-right-style NONE
set -g message-style "bg=#5b6078,fg=#cad3f5"
set -g message-command-style "bg=#1e2030,fg=#cad3f5"
set -g pane-border-style "fg=#5b6078"
set -g pane-active-border-style "fg=#8aadf4"
set -g window-status-activity-style "fg=#cad3f5,bg=#1e2030"
set -g window-status-style "fg=#cad3f5,bg=#1e2030"
set -g window-status-current-format "#[fg=#1e2030,bg=#8aadf4,bold] #I #[fg=#cad3f5,bg=#1e2030] #W #F "
set -g window-status-format "#[fg=#cad3f5,bg=#1e2030] #I #[fg=#cad3f5,bg=#1e2030] #W #F "
set -g status-left "#[fg=#1e2030,bg=#8aadf4,bold] #S #[fg=#8aadf4,bg=#1e2030]"
set -g status-right "#[fg=#a6da95,bg=#1e2030] %Y-%m-%d #[fg=#8aadf4,bg=#1e2030]  #[fg=#1e2030,bg=#8aadf4,bold] %H:%M "
set -g mode-style "fg=#a6da95,bg=#1e2030"
set -g window-status-bell-style "fg=#ed8796,bg=#1e2030,bold"
