set -g status-style "bg=#282A36,fg=#F8F8F2"
set -g status-left-style NONE
set -g status-right-style NONE
set -g message-style "bg=#BD93F9,fg=#F8F8F2"
set -g message-command-style "bg=#282A36,fg=#F8F8F2"
set -g pane-border-style "fg=#F8F8F2"
set -g pane-active-border-style "fg=#BD93F9"
set -g window-status-activity-style "fg=#F8F8F2,bg=#282A36"
set -g window-status-style "fg=#F8F8F2,bg=#282A36"
set -g window-status-current-format "#[fg=#282A36,bg=#BD93F9,bold] #I #[fg=#F8F8F2,bg=#282A36] #W #F "
set -g window-status-format "#[fg=#F8F8F2,bg=#282A36] #I #[fg=#F8F8F2,bg=#282A36] #W #F "
set -g status-left "#[fg=#282A36,bg=#BD93F9,bold] #S #[fg=#BD93F9,bg=#282A36]"
set -g status-right "#[fg=#50fa7b,bg=#282A36] %Y-%m-%d #[fg=#BD93F9,bg=#282A36]  #[fg=#282A36,bg=#BD93F9,bold] %H:%M "
set -g mode-style "fg=#50fa7b,bg=#282A36"
set -g window-status-bell-style "fg=#FF5555,bg=#282A36,bold"
