set -g status-style "bg=#3a464c,fg=#d3c6aa"
set -g status-left-style NONE
set -g status-right-style NONE
set -g message-style "bg=#5c3f4f,fg=#d3c6aa"
set -g message-command-style "bg=#3a464c,fg=#d3c6aa"
set -g pane-border-style "fg=#d3c6aa"
set -g pane-active-border-style "fg=#7fbbb3"
set -g window-status-activity-style "fg=#d3c6aa,bg=#3a464c"
set -g window-status-style "fg=#d3c6aa,bg=#3a464c"
set -g window-status-current-format "#[fg=#3a464c,bg=#7fbbb3,bold] #I #[fg=#d3c6aa,bg=#3a464c] #W #F "
set -g window-status-format "#[fg=#d3c6aa,bg=#3a464c] #I #[fg=#d3c6aa,bg=#3a464c] #W #F "
set -g status-left "#[fg=#3a464c,bg=#7fbbb3,bold] #S #[fg=#7fbbb3,bg=#3a464c]"
set -g status-right "#[fg=#a7c080,bg=#3a464c] %Y-%m-%d #[fg=#7fbbb3,bg=#3a464c]  #[fg=#3a464c,bg=#7fbbb3,bold] %H:%M "
set -g mode-style "fg=#a7c080,bg=#3a464c"
set -g window-status-bell-style "fg=#e67e80,bg=#3a464c,bold"
