set -g status-style "bg=#2e383c,fg=#d3c6aa"
set -g status-left-style NONE
set -g status-right-style NONE
set -g message-style "bg=#4c3743,fg=#d3c6aa"
set -g message-command-style "bg=#2e383c,fg=#d3c6aa"
set -g pane-border-style "fg=#d3c6aa"
set -g pane-active-border-style "fg=#7fbbb3"
set -g window-status-activity-style "fg=#d3c6aa,bg=#2e383c"
set -g window-status-style "fg=#d3c6aa,bg=#2e383c"
set -g window-status-current-format "#[fg=#2e383c,bg=#7fbbb3,bold] #I #[fg=#d3c6aa,bg=#2e383c] #W #F "
set -g window-status-format "#[fg=#d3c6aa,bg=#2e383c] #I #[fg=#d3c6aa,bg=#2e383c] #W #F "
set -g status-left "#[fg=#2e383c,bg=#7fbbb3,bold] #S #[fg=#7fbbb3,bg=#2e383c]"
set -g status-right "#[fg=#a7c080,bg=#2e383c] %Y-%m-%d #[fg=#7fbbb3,bg=#2e383c]  #[fg=#2e383c,bg=#7fbbb3,bold] %H:%M "
set -g mode-style "fg=#a7c080,bg=#2e383c"
set -g window-status-bell-style "fg=#e67e80,bg=#2e383c,bold"
