set -g status-style "bg=#343f44,fg=#d3c6aa"
set -g status-left-style NONE
set -g status-right-style NONE
set -g message-style "bg=#543a48,fg=#d3c6aa"
set -g message-command-style "bg=#343f44,fg=#d3c6aa"
set -g pane-border-style "fg=#d3c6aa"
set -g pane-active-border-style "fg=#7fbbb3"
set -g window-status-activity-style "fg=#d3c6aa,bg=#343f44"
set -g window-status-style "fg=#d3c6aa,bg=#343f44"
set -g window-status-current-format "#[fg=#343f44,bg=#7fbbb3,bold] #I #[fg=#d3c6aa,bg=#343f44] #W #F "
set -g window-status-format "#[fg=#d3c6aa,bg=#343f44] #I #[fg=#d3c6aa,bg=#343f44] #W #F "
set -g status-left "#[fg=#343f44,bg=#7fbbb3,bold] #S #[fg=#7fbbb3,bg=#343f44]"
set -g status-right "#[fg=#a7c080,bg=#343f44] %Y-%m-%d #[fg=#7fbbb3,bg=#343f44]  #[fg=#343f44,bg=#7fbbb3,bold] %H:%M "
set -g mode-style "fg=#a7c080,bg=#343f44"
set -g window-status-bell-style "fg=#e67e80,bg=#343f44,bold"
