set -g status-style "bg=#eae4ca,fg=#5c6a72"
set -g status-left-style NONE
set -g status-right-style NONE
set -g message-style "bg=#e1e4bd,fg=#5c6a72"
set -g message-command-style "bg=#eae4ca,fg=#5c6a72"
set -g pane-border-style "fg=#5c6a72"
set -g pane-active-border-style "fg=#3a94c5"
set -g window-status-activity-style "fg=#5c6a72,bg=#eae4ca"
set -g window-status-style "fg=#5c6a72,bg=#eae4ca"
set -g window-status-current-format "#[fg=#eae4ca,bg=#3a94c5,bold] #I #[fg=#5c6a72,bg=#eae4ca] #W #F "
set -g window-status-format "#[fg=#5c6a72,bg=#eae4ca] #I #[fg=#5c6a72,bg=#eae4ca] #W #F "
set -g status-left "#[fg=#eae4ca,bg=#3a94c5,bold] #S #[fg=#3a94c5,bg=#eae4ca]"
set -g status-right "#[fg=#8da101,bg=#eae4ca] %Y-%m-%d #[fg=#3a94c5,bg=#eae4ca]  #[fg=#eae4ca,bg=#3a94c5,bold] %H:%M "
set -g mode-style "fg=#8da101,bg=#eae4ca"
set -g window-status-bell-style "fg=#f85552,bg=#eae4ca,bold"
