set -g status-style "bg=#152528,fg=#e6eaea"
set -g status-left-style NONE
set -g status-right-style NONE
set -g message-style "bg=dim: "#4d7d90"
base: "#5a93aa"
light: false
bright: "#73a3b7,fg=#e6eaea"
set -g message-command-style "bg=#152528,fg=#e6eaea"
set -g pane-border-style "fg=#e6eaea"
set -g pane-active-border-style "fg=dim: "#4d7d90"
base: "#5a93aa"
light: false
bright: "#73a3b7"
set -g window-status-activity-style "fg=#e6eaea,bg=#152528"
set -g window-status-style "fg=#e6eaea,bg=#152528"
set -g window-status-current-format "#[fg=#152528,bg=dim: "#4d7d90"
base: "#5a93aa"
light: false
bright: "#73a3b7,bold] #I #[fg=#e6eaea,bg=#152528] #W #F "
set -g window-status-format "#[fg=#e6eaea,bg=#152528] #I #[fg=#e6eaea,bg=#152528] #W #F "
set -g status-left "#[fg=#152528,bg=dim: "#4d7d90"
base: "#5a93aa"
light: false
bright: "#73a3b7,bold] #S #[fg=dim: "#4d7d90"
base: "#5a93aa"
light: false
bright: "#73a3b7,bg=#152528]"
set -g status-right "#[fg=dim: "#688b89"
base: "#7aa4a1"
light: false
bright: "#8eb2af,bg=#152528] %Y-%m-%d #[fg=dim: "#4d7d90"
base: "#5a93aa"
light: false
bright: "#73a3b7,bg=#152528]  #[fg=#152528,bg=dim: "#4d7d90"
base: "#5a93aa"
light: false
bright: "#73a3b7,bold] %H:%M "
set -g mode-style "fg=dim: "#688b89"
base: "#7aa4a1"
light: false
bright: "#8eb2af,bg=#152528"
set -g window-status-bell-style "fg=dim: "#c54e45"
base: "#e85c51"
light: false
bright: "#eb746b,bg=#152528,bold"
