set -g status-style "bg=#2e3440,fg=#cdcecf"
set -g status-left-style NONE
set -g status-right-style NONE
set -g message-style "bg=dim: "#668aab"
base: "#81a1c1"
light: false
bright: "#8cafd2,fg=#cdcecf"
set -g message-command-style "bg=#2e3440,fg=#cdcecf"
set -g pane-border-style "fg=#cdcecf"
set -g pane-active-border-style "fg=dim: "#668aab"
base: "#81a1c1"
light: false
bright: "#8cafd2"
set -g window-status-activity-style "fg=#cdcecf,bg=#2e3440"
set -g window-status-style "fg=#cdcecf,bg=#2e3440"
set -g window-status-current-format "#[fg=#2e3440,bg=dim: "#668aab"
base: "#81a1c1"
light: false
bright: "#8cafd2,bold] #I #[fg=#cdcecf,bg=#2e3440] #W #F "
set -g window-status-format "#[fg=#cdcecf,bg=#2e3440] #I #[fg=#cdcecf,bg=#2e3440] #W #F "
set -g status-left "#[fg=#2e3440,bg=dim: "#668aab"
base: "#81a1c1"
light: false
bright: "#8cafd2,bold] #S #[fg=dim: "#668aab"
base: "#81a1c1"
light: false
bright: "#8cafd2,bg=#2e3440]"
set -g status-right "#[fg=dim: "#8aa872"
base: "#a3be8c"
light: false
bright: "#b1d196,bg=#2e3440] %Y-%m-%d #[fg=dim: "#668aab"
base: "#81a1c1"
light: false
bright: "#8cafd2,bg=#2e3440]  #[fg=#2e3440,bg=dim: "#668aab"
base: "#81a1c1"
light: false
bright: "#8cafd2,bold] %H:%M "
set -g mode-style "fg=dim: "#8aa872"
base: "#a3be8c"
light: false
bright: "#b1d196,bg=#2e3440"
set -g window-status-bell-style "fg=dim: "#a54e56"
base: "#bf616a"
light: false
bright: "#d06f79,bg=#2e3440,bold"
