set -g status-style "bg=#192330,fg=#cdcecf"
set -g status-left-style NONE
set -g status-right-style NONE
set -g message-style "bg=dim: "#6085b6"
base: "#719cd6"
light: false
bright: "#86abdc,fg=#cdcecf"
set -g message-command-style "bg=#192330,fg=#cdcecf"
set -g pane-border-style "fg=#cdcecf"
set -g pane-active-border-style "fg=dim: "#6085b6"
base: "#719cd6"
light: false
bright: "#86abdc"
set -g window-status-activity-style "fg=#cdcecf,bg=#192330"
set -g window-status-style "fg=#cdcecf,bg=#192330"
set -g window-status-current-format "#[fg=#192330,bg=dim: "#6085b6"
base: "#719cd6"
light: false
bright: "#86abdc,bold] #I #[fg=#cdcecf,bg=#192330] #W #F "
set -g window-status-format "#[fg=#cdcecf,bg=#192330] #I #[fg=#cdcecf,bg=#192330] #W #F "
set -g status-left "#[fg=#192330,bg=dim: "#6085b6"
base: "#719cd6"
light: false
bright: "#86abdc,bold] #S #[fg=dim: "#6085b6"
base: "#719cd6"
light: false
bright: "#86abdc,bg=#192330]"
set -g status-right "#[fg=dim: "#6e9783"
base: "#81b29a"
light: false
bright: "#8ebaa4,bg=#192330] %Y-%m-%d #[fg=dim: "#6085b6"
base: "#719cd6"
light: false
bright: "#86abdc,bg=#192330]  #[fg=#192330,bg=dim: "#6085b6"
base: "#719cd6"
light: false
bright: "#86abdc,bold] %H:%M "
set -g mode-style "fg=dim: "#6e9783"
base: "#81b29a"
light: false
bright: "#8ebaa4,bg=#192330"
set -g window-status-bell-style "fg=dim: "#ab435d"
base: "#c94f6d"
light: false
bright: "#d16983,bg=#192330,bold"
