set -g status-style "bg=#232136,fg=#e0def4"
set -g status-left-style NONE
set -g status-right-style NONE
set -g message-style "bg=dim: "#4a869c"
base: "#569fba"
light: false
bright: "#65b1cd,fg=#e0def4"
set -g message-command-style "bg=#232136,fg=#e0def4"
set -g pane-border-style "fg=#e0def4"
set -g pane-active-border-style "fg=dim: "#4a869c"
base: "#569fba"
light: false
bright: "#65b1cd"
set -g window-status-activity-style "fg=#e0def4,bg=#232136"
set -g window-status-style "fg=#e0def4,bg=#232136"
set -g window-status-current-format "#[fg=#232136,bg=dim: "#4a869c"
base: "#569fba"
light: false
bright: "#65b1cd,bold] #I #[fg=#e0def4,bg=#232136] #W #F "
set -g window-status-format "#[fg=#e0def4,bg=#232136] #I #[fg=#e0def4,bg=#232136] #W #F "
set -g status-left "#[fg=#232136,bg=dim: "#4a869c"
base: "#569fba"
light: false
bright: "#65b1cd,bold] #S #[fg=dim: "#4a869c"
base: "#569fba"
light: false
bright: "#65b1cd,bg=#232136]"
set -g status-right "#[fg=dim: "#8aa872"
base: "#a3be8c"
light: false
bright: "#b1d196,bg=#232136] %Y-%m-%d #[fg=dim: "#4a869c"
base: "#569fba"
light: false
bright: "#65b1cd,bg=#232136]  #[fg=#232136,bg=dim: "#4a869c"
base: "#569fba"
light: false
bright: "#65b1cd,bold] %H:%M "
set -g mode-style "fg=dim: "#8aa872"
base: "#a3be8c"
light: false
bright: "#b1d196,bg=#232136"
set -g window-status-bell-style "fg=dim: "#d84f76"
base: "#eb6f92"
light: false
bright: "#f083a2,bg=#232136,bold"
