set -g status-style "bg=#faf4ed,fg=#575279"
set -g status-left-style NONE
set -g status-right-style NONE
set -g message-style "bg=dim: "#295e73"
base: "#286983"
light: true
bright: "#2d81a3,fg=#575279"
set -g message-command-style "bg=#faf4ed,fg=#575279"
set -g pane-border-style "fg=#575279"
set -g pane-active-border-style "fg=dim: "#295e73"
base: "#286983"
light: true
bright: "#2d81a3"
set -g window-status-activity-style "fg=#575279,bg=#faf4ed"
set -g window-status-style "fg=#575279,bg=#faf4ed"
set -g window-status-current-format "#[fg=#faf4ed,bg=dim: "#295e73"
base: "#286983"
light: true
bright: "#2d81a3,bold] #I #[fg=#575279,bg=#faf4ed] #W #F "
set -g window-status-format "#[fg=#575279,bg=#faf4ed] #I #[fg=#575279,bg=#faf4ed] #W #F "
set -g status-left "#[fg=#faf4ed,bg=dim: "#295e73"
base: "#286983"
light: true
bright: "#2d81a3,bold] #S #[fg=dim: "#295e73"
base: "#286983"
light: true
bright: "#2d81a3,bg=#faf4ed]"
set -g status-right "#[fg=dim: "#597668"
base: "#618774"
light: true
bright: "#629f81,bg=#faf4ed] %Y-%m-%d #[fg=dim: "#295e73"
base: "#286983"
light: true
bright: "#2d81a3,bg=#faf4ed]  #[fg=#faf4ed,bg=dim: "#295e73"
base: "#286983"
light: true
bright: "#2d81a3,bold] %H:%M "
set -g mode-style "fg=dim: "#597668"
base: "#618774"
light: true
bright: "#629f81,bg=#faf4ed"
set -g window-status-bell-style "fg=dim: "#a5576d"
base: "#b4637a"
light: true
bright: "#c26d85,bg=#faf4ed,bold"
