set -g status-style "bg=#f6f2ee,fg=#3d2b5a"
set -g status-left-style NONE
set -g status-right-style NONE
set -g message-style "bg=dim: "#223d90"
base: "#2848a9"
light: true
bright: "#4863b6,fg=#3d2b5a"
set -g message-command-style "bg=#f6f2ee,fg=#3d2b5a"
set -g pane-border-style "fg=#3d2b5a"
set -g pane-active-border-style "fg=dim: "#223d90"
base: "#2848a9"
light: true
bright: "#4863b6"
set -g window-status-activity-style "fg=#3d2b5a,bg=#f6f2ee"
set -g window-status-style "fg=#3d2b5a,bg=#f6f2ee"
set -g window-status-current-format "#[fg=#f6f2ee,bg=dim: "#223d90"
base: "#2848a9"
light: true
bright: "#4863b6,bold] #I #[fg=#3d2b5a,bg=#f6f2ee] #W #F "
set -g window-status-format "#[fg=#3d2b5a,bg=#f6f2ee] #I #[fg=#3d2b5a,bg=#f6f2ee] #W #F "
set -g status-left "#[fg=#f6f2ee,bg=dim: "#223d90"
base: "#2848a9"
light: true
bright: "#4863b6,bold] #S #[fg=dim: "#223d90"
base: "#2848a9"
light: true
bright: "#4863b6,bg=#f6f2ee]"
set -g status-right "#[fg=dim: "#30583c"
base: "#396847"
light: true
bright: "#577f63,bg=#f6f2ee] %Y-%m-%d #[fg=dim: "#223d90"
base: "#2848a9"
light: true
bright: "#4863b6,bg=#f6f2ee]  #[fg=#f6f2ee,bg=dim: "#223d90"
base: "#2848a9"
light: true
bright: "#4863b6,bold] %H:%M "
set -g mode-style "fg=dim: "#30583c"
base: "#396847"
light: true
bright: "#577f63,bg=#f6f2ee"
set -g window-status-bell-style "fg=dim: "#8c1d28"
base: "#a5222f"
light: true
bright: "#b3434e,bg=#f6f2ee,bold"
