set -g status-style "bg=#282c34,fg=#abb2bf"
set -g status-left-style NONE
set -g status-right-style NONE
set -g message-style "bg=#61afef,fg=#abb2bf"
set -g message-command-style "bg=#282c34,fg=#abb2bf"
set -g pane-border-style "fg=#5c6370"
set -g pane-active-border-style "fg=#61afef"
set -g window-status-activity-style "fg=#abb2bf,bg=#282c34"
set -g window-status-style "fg=#abb2bf,bg=#282c34"
set -g window-status-current-format "#[fg=#282c34,bg=#61afef,bold] #I #[fg=#abb2bf,bg=#282c34] #W #F "
set -g window-status-format "#[fg=#abb2bf,bg=#282c34] #I #[fg=#abb2bf,bg=#282c34] #W #F "
set -g status-left "#[fg=#282c34,bg=#61afef,bold] #S #[fg=#61afef,bg=#282c34]"
set -g status-right "#[fg=#89ca78,bg=#282c34] %Y-%m-%d #[fg=#61afef,bg=#282c34]  #[fg=#282c34,bg=#61afef,bold] %H:%M "
set -g mode-style "fg=#89ca78,bg=#282c34"
set -g window-status-bell-style "fg=#ef596f,bg=#282c34,bold"
