set -g status-style "bg=#fafafa,fg=#6a6a6a"
set -g status-left-style NONE
set -g status-right-style NONE
set -g message-style "bg=#118dc3,fg=#6a6a6a"
set -g message-command-style "bg=#fafafa,fg=#6a6a6a"
set -g pane-border-style "fg=#bebebe"
set -g pane-active-border-style "fg=#118dc3"
set -g window-status-activity-style "fg=#6a6a6a,bg=#fafafa"
set -g window-status-style "fg=#6a6a6a,bg=#fafafa"
set -g window-status-current-format "#[fg=#fafafa,bg=#118dc3,bold] #I #[fg=#6a6a6a,bg=#fafafa] #W #F "
set -g window-status-format "#[fg=#6a6a6a,bg=#fafafa] #I #[fg=#6a6a6a,bg=#fafafa] #W #F "
set -g status-left "#[fg=#fafafa,bg=#118dc3,bold] #S #[fg=#118dc3,bg=#fafafa]"
set -g status-right "#[fg=#1da912,bg=#fafafa] %Y-%m-%d #[fg=#118dc3,bg=#fafafa]  #[fg=#fafafa,bg=#118dc3,bold] %H:%M "
set -g mode-style "fg=#1da912,bg=#fafafa"
set -g window-status-bell-style "fg=#e05661,bg=#fafafa,bold"
