set -g status-style "bg=#000000,fg=#abb2bf"
set -g status-left-style NONE
set -g status-right-style NONE
set -g message-style "bg=#61afef,fg=#abb2bf"
set -g message-command-style "bg=#000000,fg=#abb2bf"
set -g pane-border-style "fg=#434852"
set -g pane-active-border-style "fg=#61afef"
set -g window-status-activity-style "fg=#abb2bf,bg=#000000"
set -g window-status-style "fg=#abb2bf,bg=#000000"
set -g window-status-current-format "#[fg=#000000,bg=#61afef,bold] #I #[fg=#abb2bf,bg=#000000] #W #F "
set -g window-status-format "#[fg=#abb2bf,bg=#000000] #I #[fg=#abb2bf,bg=#000000] #W #F "
set -g status-left "#[fg=#000000,bg=#61afef,bold] #S #[fg=#61afef,bg=#000000]"
set -g status-right "#[fg=#89ca78,bg=#000000] %Y-%m-%d #[fg=#61afef,bg=#000000]  #[fg=#000000,bg=#61afef,bold] %H:%M "
set -g mode-style "fg=#89ca78,bg=#000000"
set -g window-status-bell-style "fg=#ef596f,bg=#000000,bold"
