set -g status-style "bg=#002c38,fg=#839395"
set -g status-left-style NONE
set -g status-right-style NONE
set -g message-style "bg=#002c38,fg=#839395"
set -g message-command-style "bg=#002c38,fg=#839395"
set -g pane-border-style "fg=#001014"
set -g pane-active-border-style "fg=#268bd3"
set -g window-status-activity-style "fg=#839395,bg=#002c38"
set -g window-status-style "fg=#839395,bg=#002c38"
set -g window-status-current-format "#[fg=#002c38,bg=#268bd3,bold] #I #[fg=#839395,bg=#002c38] #W #F "
set -g window-status-format "#[fg=#839395,bg=#002c38] #I #[fg=#839395,bg=#002c38] #W #F "
set -g status-left "#[fg=#002c38,bg=#268bd3,bold] #S #[fg=#268bd3,bg=#002c38]"
set -g status-right "#[fg=#849900,bg=#002c38] %Y-%m-%d #[fg=#268bd3,bg=#002c38]  #[fg=#002c38,bg=#268bd3,bold] %H:%M "
set -g mode-style "fg=#849900,bg=#002c38"
set -g window-status-bell-style "fg=#db302d,bg=#002c38,bold"
