set -g status-style "bg=#d0d5e3,fg=#3760bf"
set -g status-left-style NONE
set -g status-right-style NONE
set -g message-style "bg=#c4c8da,fg=#3760bf"
set -g message-command-style "bg=#d0d5e3,fg=#3760bf"
set -g pane-border-style "fg=#b4b5b9"
set -g pane-active-border-style "fg=#2e7de9"
set -g window-status-activity-style "fg=#3760bf,bg=#d0d5e3"
set -g window-status-style "fg=#3760bf,bg=#d0d5e3"
set -g window-status-current-format "#[fg=#d0d5e3,bg=#2e7de9,bold] #I #[fg=#3760bf,bg=#d0d5e3] #W #F "
set -g window-status-format "#[fg=#3760bf,bg=#d0d5e3] #I #[fg=#3760bf,bg=#d0d5e3] #W #F "
set -g status-left "#[fg=#d0d5e3,bg=#2e7de9,bold] #S #[fg=#2e7de9,bg=#d0d5e3]"
set -g status-right "#[fg=#587539,bg=#d0d5e3] %Y-%m-%d #[fg=#2e7de9,bg=#d0d5e3]  #[fg=#d0d5e3,bg=#2e7de9,bold] %H:%M "
set -g mode-style "fg=#587539,bg=#d0d5e3"
set -g window-status-bell-style "fg=#f52a65,bg=#d0d5e3,bold"
