set -g status-style "bg=#1e2030,fg=#c8d3f5"
set -g status-left-style NONE
set -g status-right-style NONE
set -g message-style "bg=#2f334d,fg=#c8d3f5"
set -g message-command-style "bg=#1e2030,fg=#c8d3f5"
set -g pane-border-style "fg=#1b1d2b"
set -g pane-active-border-style "fg=#82aaff"
set -g window-status-activity-style "fg=#c8d3f5,bg=#1e2030"
set -g window-status-style "fg=#c8d3f5,bg=#1e2030"
set -g window-status-current-format "#[fg=#1e2030,bg=#82aaff,bold] #I #[fg=#c8d3f5,bg=#1e2030] #W #F "
set -g window-status-format "#[fg=#c8d3f5,bg=#1e2030] #I #[fg=#c8d3f5,bg=#1e2030] #W #F "
set -g status-left "#[fg=#1e2030,bg=#82aaff,bold] #S #[fg=#82aaff,bg=#1e2030]"
set -g status-right "#[fg=#c3e88d,bg=#1e2030] %Y-%m-%d #[fg=#82aaff,bg=#1e2030]  #[fg=#1e2030,bg=#82aaff,bold] %H:%M "
set -g mode-style "fg=#c3e88d,bg=#1e2030"
set -g window-status-bell-style "fg=#ff757f,bg=#1e2030,bold"
