set -g status-style "bg=#1f2335,fg=#c0caf5"
set -g status-left-style NONE
set -g status-right-style NONE
set -g message-style "bg=#292e42,fg=#c0caf5"
set -g message-command-style "bg=#1f2335,fg=#c0caf5"
set -g pane-border-style "fg=#1d202f"
set -g pane-active-border-style "fg=#7aa2f7"
set -g window-status-activity-style "fg=#c0caf5,bg=#1f2335"
set -g window-status-style "fg=#c0caf5,bg=#1f2335"
set -g window-status-current-format "#[fg=#1f2335,bg=#7aa2f7,bold] #I #[fg=#c0caf5,bg=#1f2335] #W #F "
set -g window-status-format "#[fg=#c0caf5,bg=#1f2335] #I #[fg=#c0caf5,bg=#1f2335] #W #F "
set -g status-left "#[fg=#1f2335,bg=#7aa2f7,bold] #S #[fg=#7aa2f7,bg=#1f2335]"
set -g status-right "#[fg=#9ece6a,bg=#1f2335] %Y-%m-%d #[fg=#7aa2f7,bg=#1f2335]  #[fg=#1f2335,bg=#7aa2f7,bold] %H:%M "
set -g mode-style "fg=#9ece6a,bg=#1f2335"
set -g window-status-bell-style "fg=#f7768e,bg=#1f2335,bold"
