set -g status-style "bg=#16161e,fg=#c0caf5"
set -g status-left-style NONE
set -g status-right-style NONE
set -g message-style "bg=#292e42,fg=#c0caf5"
set -g message-command-style "bg=#16161e,fg=#c0caf5"
set -g pane-border-style "fg=#15161e"
set -g pane-active-border-style "fg=#7aa2f7"
set -g window-status-activity-style "fg=#c0caf5,bg=#16161e"
set -g window-status-style "fg=#c0caf5,bg=#16161e"
set -g window-status-current-format "#[fg=#16161e,bg=#7aa2f7,bold] #I #[fg=#c0caf5,bg=#16161e] #W #F "
set -g window-status-format "#[fg=#c0caf5,bg=#16161e] #I #[fg=#c0caf5,bg=#16161e] #W #F "
set -g status-left "#[fg=#16161e,bg=#7aa2f7,bold] #S #[fg=#7aa2f7,bg=#16161e]"
set -g status-right "#[fg=#9ece6a,bg=#16161e] %Y-%m-%d #[fg=#7aa2f7,bg=#16161e]  #[fg=#16161e,bg=#7aa2f7,bold] %H:%M "
set -g mode-style "fg=#9ece6a,bg=#16161e"
set -g window-status-bell-style "fg=#f7768e,bg=#16161e,bold"
