set -g status-style "bg=#1F1F28,fg=#DDD8BB"
set -g status-left-style NONE
set -g status-right-style NONE
set -g message-style "bg=#7EB3C9,fg=#DDD8BB"
set -g message-command-style "bg=#1F1F28,fg=#DDD8BB"
set -g pane-border-style "fg=#A8A48D"
set -g pane-active-border-style "fg=#7EB3C9"
set -g window-status-activity-style "fg=#DDD8BB,bg=#1F1F28"
set -g window-status-style "fg=#DDD8BB,bg=#1F1F28"
set -g window-status-current-format "#[fg=#1F1F28,bg=#7EB3C9,bold] #I #[fg=#DDD8BB,bg=#1F1F28] #W #F "
set -g window-status-format "#[fg=#DDD8BB,bg=#1F1F28] #I #[fg=#DDD8BB,bg=#1F1F28] #W #F "
set -g status-left "#[fg=#1F1F28,bg=#7EB3C9,bold] #S #[fg=#7EB3C9,bg=#1F1F28]"
set -g status-right "#[fg=#98BC6D,bg=#1F1F28] %Y-%m-%d #[fg=#7EB3C9,bg=#1F1F28]  #[fg=#1F1F28,bg=#7EB3C9,bold] %H:%M "
set -g mode-style "fg=#98BC6D,bg=#1F1F28"
set -g window-status-bell-style "fg=#E46A78,bg=#1F1F28,bold"
