set -g status-style "bg=#2C343A,fg=#E7DCC4"
set -g status-left-style NONE
set -g status-right-style NONE
set -g message-style "bg=#7FBCB4,fg=#E7DCC4"
set -g message-command-style "bg=#2C343A,fg=#E7DCC4"
set -g pane-border-style "fg=#B2A790"
set -g pane-active-border-style "fg=#7FBCB4"
set -g window-status-activity-style "fg=#E7DCC4,bg=#2C343A"
set -g window-status-style "fg=#E7DCC4,bg=#2C343A"
set -g window-status-current-format "#[fg=#2C343A,bg=#7FBCB4,bold] #I #[fg=#E7DCC4,bg=#2C343A] #W #F "
set -g window-status-format "#[fg=#E7DCC4,bg=#2C343A] #I #[fg=#E7DCC4,bg=#2C343A] #W #F "
set -g status-left "#[fg=#2C343A,bg=#7FBCB4,bold] #S #[fg=#7FBCB4,bg=#2C343A]"
set -g status-right "#[fg=#A9C181,bg=#2C343A] %Y-%m-%d #[fg=#7FBCB4,bg=#2C343A]  #[fg=#2C343A,bg=#7FBCB4,bold] %H:%M "
set -g mode-style "fg=#A9C181,bg=#2C343A"
set -g window-status-bell-style "fg=#E67C7F,bg=#2C343A,bold"
