set -g status-style "bg=#4B4B4B,fg=#DDDDDD"
set -g status-left-style NONE
set -g status-right-style NONE
set -g message-style "bg=#97BDDE,fg=#DDDDDD"
set -g message-command-style "bg=#4B4B4B,fg=#DDDDDD"
set -g pane-border-style "fg=#A8A8A8"
set -g pane-active-border-style "fg=#97BDDE"
set -g window-status-activity-style "fg=#DDDDDD,bg=#4B4B4B"
set -g window-status-style "fg=#DDDDDD,bg=#4B4B4B"
set -g window-status-current-format "#[fg=#4B4B4B,bg=#97BDDE,bold] #I #[fg=#DDDDDD,bg=#4B4B4B] #W #F "
set -g window-status-format "#[fg=#DDDDDD,bg=#4B4B4B] #I #[fg=#DDDDDD,bg=#4B4B4B] #W #F "
set -g status-left "#[fg=#4B4B4B,bg=#97BDDE,bold] #S #[fg=#97BDDE,bg=#4B4B4B]"
set -g status-right "#[fg=#98BD99,bg=#4B4B4B] %Y-%m-%d #[fg=#97BDDE,bg=#4B4B4B]  #[fg=#4B4B4B,bg=#97BDDE,bold] %H:%M "
set -g mode-style "fg=#98BD99,bg=#4B4B4B"
set -g window-status-bell-style "fg=#E388A3,bg=#4B4B4B,bold"
