set -g status-style "bg=#EEEEEE,fg=#353535"
set -g status-left-style NONE
set -g status-right-style NONE
set -g message-style "bg=#286486,fg=#353535"
set -g message-command-style "bg=#EEEEEE,fg=#353535"
set -g pane-border-style "fg=#5C5C5C"
set -g pane-active-border-style "fg=#286486"
set -g window-status-activity-style "fg=#353535,bg=#EEEEEE"
set -g window-status-style "fg=#353535,bg=#EEEEEE"
set -g window-status-current-format "#[fg=#EEEEEE,bg=#286486,bold] #I #[fg=#353535,bg=#EEEEEE] #W #F "
set -g window-status-format "#[fg=#353535,bg=#EEEEEE] #I #[fg=#353535,bg=#EEEEEE] #W #F "
set -g status-left "#[fg=#EEEEEE,bg=#286486,bold] #S #[fg=#286486,bg=#EEEEEE]"
set -g status-right "#[fg=#4F6C31,bg=#EEEEEE] %Y-%m-%d #[fg=#286486,bg=#EEEEEE]  #[fg=#EEEEEE,bg=#286486,bold] %H:%M "
set -g mode-style "fg=#4F6C31,bg=#EEEEEE"
set -g window-status-bell-style "fg=#A8334C,bg=#EEEEEE,bold"
