set -g status-style "bg=#1A1825,fg=#E1D4D4"
set -g status-left-style NONE
set -g status-right-style NONE
set -g message-style "bg=#9CCFD8,fg=#E1D4D4"
set -g message-command-style "bg=#1A1825,fg=#E1D4D4"
set -g pane-border-style "fg=#BF9B99"
set -g pane-active-border-style "fg=#9CCFD8"
set -g window-status-activity-style "fg=#E1D4D4,bg=#1A1825"
set -g window-status-style "fg=#E1D4D4,bg=#1A1825"
set -g window-status-current-format "#[fg=#1A1825,bg=#9CCFD8,bold] #I #[fg=#E1D4D4,bg=#1A1825] #W #F "
set -g window-status-format "#[fg=#E1D4D4,bg=#1A1825] #I #[fg=#E1D4D4,bg=#1A1825] #W #F "
set -g status-left "#[fg=#1A1825,bg=#9CCFD8,bold] #S #[fg=#9CCFD8,bg=#1A1825]"
set -g status-right "#[fg=#317490,bg=#1A1825] %Y-%m-%d #[fg=#9CCFD8,bg=#1A1825]  #[fg=#1A1825,bg=#9CCFD8,bold] %H:%M "
set -g mode-style "fg=#317490,bg=#1A1825"
set -g window-status-bell-style "fg=#EB7193,bg=#1A1825,bold"
