set -g status-style "bg=#1A1B26,fg=#C0CAF5"
set -g status-left-style NONE
set -g status-right-style NONE
set -g message-style "bg=#7BA2F7,fg=#C0CAF5"
set -g message-command-style "bg=#1A1B26,fg=#C0CAF5"
set -g pane-border-style "fg=#7E98EB"
set -g pane-active-border-style "fg=#7BA2F7"
set -g window-status-activity-style "fg=#C0CAF5,bg=#1A1B26"
set -g window-status-style "fg=#C0CAF5,bg=#1A1B26"
set -g window-status-current-format "#[fg=#1A1B26,bg=#7BA2F7,bold] #I #[fg=#C0CAF5,bg=#1A1B26] #W #F "
set -g window-status-format "#[fg=#C0CAF5,bg=#1A1B26] #I #[fg=#C0CAF5,bg=#1A1B26] #W #F "
set -g status-left "#[fg=#1A1B26,bg=#7BA2F7,bold] #S #[fg=#7BA2F7,bg=#1A1B26]"
set -g status-right "#[fg=#74DBCB,bg=#1A1B26] %Y-%m-%d #[fg=#7BA2F7,bg=#1A1B26]  #[fg=#1A1B26,bg=#7BA2F7,bold] %H:%M "
set -g mode-style "fg=#74DBCB,bg=#1A1B26"
set -g window-status-bell-style "fg=#F77890,bg=#1A1B26,bold"
