set -g status-style "bg=#0F191F,fg=#C6D5CF"
set -g status-left-style NONE
set -g status-right-style NONE
set -g message-style "bg=#8190D4,fg=#C6D5CF"
set -g message-command-style "bg=#0F191F,fg=#C6D5CF"
set -g pane-border-style "fg=#98A39E"
set -g pane-active-border-style "fg=#8190D4"
set -g window-status-activity-style "fg=#C6D5CF,bg=#0F191F"
set -g window-status-style "fg=#C6D5CF,bg=#0F191F"
set -g window-status-current-format "#[fg=#0F191F,bg=#8190D4,bold] #I #[fg=#C6D5CF,bg=#0F191F] #W #F "
set -g window-status-format "#[fg=#C6D5CF,bg=#0F191F] #I #[fg=#C6D5CF,bg=#0F191F] #W #F "
set -g status-left "#[fg=#0F191F,bg=#8190D4,bold] #S #[fg=#8190D4,bg=#0F191F]"
set -g status-right "#[fg=#90FF6B,bg=#0F191F] %Y-%m-%d #[fg=#8190D4,bg=#0F191F]  #[fg=#0F191F,bg=#8190D4,bold] %H:%M "
set -g mode-style "fg=#90FF6B,bg=#0F191F"
set -g window-status-bell-style "fg=#DE6E7C,bg=#0F191F,bold"
