set -g status-style "bg=#1C1917,fg=#B4BDC3"
set -g status-left-style NONE
set -g status-right-style NONE
set -g message-style "bg=#6099C0,fg=#B4BDC3"
set -g message-command-style "bg=#1C1917,fg=#B4BDC3"
set -g pane-border-style "fg=#888F94"
set -g pane-active-border-style "fg=#6099C0"
set -g window-status-activity-style "fg=#B4BDC3,bg=#1C1917"
set -g window-status-style "fg=#B4BDC3,bg=#1C1917"
set -g window-status-current-format "#[fg=#1C1917,bg=#6099C0,bold] #I #[fg=#B4BDC3,bg=#1C1917] #W #F "
set -g window-status-format "#[fg=#B4BDC3,bg=#1C1917] #I #[fg=#B4BDC3,bg=#1C1917] #W #F "
set -g status-left "#[fg=#1C1917,bg=#6099C0,bold] #S #[fg=#6099C0,bg=#1C1917]"
set -g status-right "#[fg=#819B69,bg=#1C1917] %Y-%m-%d #[fg=#6099C0,bg=#1C1917]  #[fg=#1C1917,bg=#6099C0,bold] %H:%M "
set -g mode-style "fg=#819B69,bg=#1C1917"
set -g window-status-bell-style "fg=#DE6E7C,bg=#1C1917,bold"
