set -g status-style "bg=#2F3541,fg=#EBEEF3"
set -g status-left-style NONE
set -g status-right-style NONE
set -g message-style "bg=#8FBCBA,fg=#EBEEF3"
set -g message-command-style "bg=#2F3541,fg=#EBEEF3"
set -g pane-border-style "fg=#A5B4CD"
set -g pane-active-border-style "fg=#8FBCBA"
set -g window-status-activity-style "fg=#EBEEF3,bg=#2F3541"
set -g window-status-style "fg=#EBEEF3,bg=#2F3541"
set -g window-status-current-format "#[fg=#2F3541,bg=#8FBCBA,bold] #I #[fg=#EBEEF3,bg=#2F3541] #W #F "
set -g window-status-format "#[fg=#EBEEF3,bg=#2F3541] #I #[fg=#EBEEF3,bg=#2F3541] #W #F "
set -g status-left "#[fg=#2F3541,bg=#8FBCBA,bold] #S #[fg=#8FBCBA,bg=#2F3541]"
set -g status-right "#[fg=#A4BE8D,bg=#2F3541] %Y-%m-%d #[fg=#8FBCBA,bg=#2F3541]  #[fg=#2F3541,bg=#8FBCBA,bold] %H:%M "
set -g mode-style "fg=#A4BE8D,bg=#2F3541"
set -g window-status-bell-style "fg=#C1616A,bg=#2F3541,bold"
