# MIT License
#
# Copyright (c) 2025 Andrew Vasilyev <me@retran.me>
#
# @file: components/shell-essential/config/fish/conf.d/theme-colors.fish
# @brief: Meow theme color management functions for fish.
# @author: Andrew Vasilyev
# @license: MIT

# Source theme colour files (FZF_DEFAULT_OPTS, EZA_COLORS, LS_COLORS).
# These are generated by generate-theme-{fzf,eza,zsh} and activated by apply-theme-*.
function _meow_source_theme_colors --description 'Reload meow theme colour variables'
    set -l config_dir "$HOME/.config/meow"
    if set -q MEOW_CONFIG_DIR
        set config_dir "$MEOW_CONFIG_DIR"
    end

    if functions -q bass
        if test -f "$config_dir/fzf/colors.sh"
            bass source "$config_dir/fzf/colors.sh" 2>/dev/null; or true
        end
        if test -f "$config_dir/eza/colors.sh"
            bass source "$config_dir/eza/colors.sh" 2>/dev/null; or true
        end
    end

    # Apply fish-native theme colours (universal variables) if a theme file exists.
    # The apply-theme-fish script writes universal vars directly, so nothing extra needed here.
end

# meow-theme wrapper — calls the script and reloads colours afterwards.
function meow-theme --description 'Manage meow colour theme'
    set -l meow_root "$HOME/.meow"
    if set -q MEOW
        set meow_root "$MEOW"
    end

    command "$meow_root/components/shell-essential/scripts/meow-theme" $argv
    set -l exit_code $status

    if test (count $argv) -eq 0
        _meow_source_theme_colors
    else if string match -rq '^(toggle|apply|preset|auto)$' -- $argv[1]
        _meow_source_theme_colors
    end

    return $exit_code
end
