description: "Productivity applications"

depends_on:
  - components/desktop-essential
  - components/pipx

homebrew:
  packages:
    - productivity

pipx:
  packages:
    - productivity

mas:
  packages:
    - productivity

symlinks:
  - toggl-track