#!/usr/bin/env bash

# Enable strict error handling for the script.

# Prevent the script from being sourced multiple times.
if [[ -n "${_COMPONENT_TOGGL_INIT_SOURCED:-}" ]]; then
  return 0
fi
_COMPONENT_TOGGL_INIT_SOURCED=1

# Define and register Bash completion for the 'toggl' command if not already set up.
if ! command -v _toggl >/dev/null 2>&1; then
  _toggl() {
    local toggl_current_line_prefix

    # Construct the command line prefix for the 'toggl' completion generator.
    # In Bash, COMP_WORDS is an array of all words on the current command line,
    # and COMP_CWORD is the 0-based index of the word currently being completed.
    # This captures the command and its arguments up to and including the current word.
    toggl_current_line_prefix="${COMP_WORDS[*]:0:COMP_CWORD+1}"

    # Execute the completion generated by the 'toggl' command itself.
    # It is assumed that 'toggl' outputs Bash-compatible completion commands
    # when called with _TOGGL_COMPLETE=complete-bash and COMMANDLINE.
    eval "$(env COMMANDLINE="${toggl_current_line_prefix}" _TOGGL_COMPLETE=complete-bash toggl)"
  }

  # Register _toggl as the completion function for the toggl command.
  complete -F _toggl toggl
fi
